<a href="https://colab.research.google.com/github/avkaz/DeepLearningPetIdentification/blob/feat_image_processing_function/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## 1st -  Download utility.py file from github repository
## 2nd - Imports all functions from utility.py

import requests

# Correct raw URL for the utility.py file
url = "https://raw.githubusercontent.com/avkaz/DeepLearningPetIdentification/main/utility.py"

# Fetch and save the file locally
response = requests.get(url)
with open("utility.py", "wb") as f:
    f.write(response.content)


import utility
print("utility.py downloaded successfully.")

utility.py downloaded successfully.


In [2]:

data = utility.get_data()

An error occurred while fetching data: Extra data: line 138386 column 6 (char 5514340)


JSONDecodeError: Extra data: line 138386 column 6 (char 5514340)

In [3]:
data ={
    "tanyny-chomutov-2024-12-21": {
        "Jméno": "Tanyny",
        "Pohlaví": "Samec",
        "Kraj": "Ústecký",
        "Okres": "Chomutov",
        "Plemeno": "Kříženec",
        "Věk": "5 let",
        "Barva": "Černá",
        "Velikost": "Střední - 10-17kg",
        "url": "https://www.psidetektiv.cz/zvire/tanyny-chomutov-2024-12-21",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/22/img190390.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/22/img190391.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/22/img190392.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/22/img190393.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/22/img190394.jpg"
        ]
    },
    "haily-tachov-2024-12-21": {
        "Jméno": "Haily",
        "Pohlaví": "Samice",
        "Kraj": "Plzeňský",
        "Okres": "Tachov",
        "Plemeno": "Jezevčík",
        "Věk": "5 let",
        "Barva": "Tmavý divočák",
        "Velikost": "Střední - 10-17kg",
        "url": "https://www.psidetektiv.cz/zvire/haily-tachov-2024-12-21",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190383.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190384.jpg"
        ]
    },
    "egy-karlovy-vary-2024-12-17": {
        "Jméno": "Egy",
        "Pohlaví": "Samec",
        "Kraj": "Karlovarský",
        "Okres": "Karlovy Vary",
        "Plemeno": "Kříženec",
        "Věk": "cca 1 rok",
        "Barva": "Mourovatý",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/egy-karlovy-vary-2024-12-17",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190378.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190379.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190380.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190381.jpg"
        ]
    },
    "randy-vyskov-2024-12-21": {
        "Jméno": "Randy",
        "Pohlaví": "Samec",
        "Kraj": "Jihomoravský",
        "Okres": "Vyškov",
        "Plemeno": "Beagle",
        "Věk": "10 let",
        "Barva": "Trikolor",
        "Velikost": "Střední - 10-17kg",
        "url": "https://www.psidetektiv.cz/zvire/randy-vyskov-2024-12-21",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190367.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190368.jpg"
        ]
    },
    "cira-a-kaja-jihlava-2024-12-21": {
        "Jméno": "Cira a Kája",
        "Pohlaví": "Samice",
        "Kraj": "Vysočina",
        "Okres": "Jihlava",
        "Plemeno": "Border terier",
        "Věk": "3 roky",
        "Barva": "Hnědá, světle hnědá",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/cira-a-kaja-jihlava-2024-12-21",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190362.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/21/img190363.jpg"
        ]
    },
    "alfik-plzen-sever-2024-12-18": {
        "Jméno": "Alfík",
        "Pohlaví": "Samec",
        "Kraj": "Plzeňský",
        "Okres": "Plzeň-sever",
        "Plemeno": "Jezevčík",
        "Věk": "8 let",
        "Barva": "Zlatá",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/alfik-plzen-sever-2024-12-18",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190320.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190321.jpg"
        ]
    },
    "juicy-most-2024-12-20": {
        "Jméno": "Juicy",
        "Pohlaví": "Samice",
        "Kraj": "Ústecký",
        "Okres": "Most",
        "Plemeno": "Belgický grifonek",
        "Věk": "8 let",
        "Barva": "Černý s pálením",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/juicy-most-2024-12-20",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190294.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190295.jpg"
        ]
    },
    "urri-pribram-2024-12-16": {
        "Jméno": "Urri",
        "Pohlaví": "Samec",
        "Kraj": "Středočeský",
        "Okres": "Příbram",
        "Plemeno": "Německý ovčák",
        "Věk": "6 let",
        "Barva": "Vlkošedý",
        "Velikost": "Velká - 18 a více kg",
        "url": "https://www.psidetektiv.cz/zvire/urri-pribram-2024-12-16",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190256.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190257.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190258.jpg"
        ]
    },
    "fery-a-persi-praha-vychod-2024-12-20": {
        "Jméno": "Fery a Persi",
        "Pohlaví": "Samec",
        "Kraj": "Středočeský",
        "Okres": "Praha-východ",
        "Plemeno": "Německý ovčák",
        "Věk": "3 roky a 5 let",
        "Barva": "Vlkošedý",
        "Velikost": "Velká - 18 a více kg",
        "url": "https://www.psidetektiv.cz/zvire/fery-a-persi-praha-vychod-2024-12-20",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190250.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190251.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190252.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/20/img190253.jpg"
        ]
    },
    "lily-pribram-2024-12-01": {
        "Jméno": "Lily",
        "Pohlaví": "Samice",
        "Kraj": "Středočeský",
        "Okres": "Příbram",
        "Plemeno": "Kříženec",
        "Věk": "1,5 roku",
        "Barva": "Šedobílá",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/lily-pribram-2024-12-01",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190243.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190244.jpg"
        ]
    },
    "uzovka-praha-mesto-2024-12-19": {
        "Jméno": "Užovka",
        "Pohlaví": "Samice",
        "Kraj": "Praha",
        "Okres": "Praha-město",
        "Plemeno": "Border kolie",
        "Věk": "necelé 4 měsíce",
        "Barva": "černo bílá",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/uzovka-praha-mesto-2024-12-19",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190237.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190238.jpg"
        ]
    },
    "endy-olomouc-2024-12-19": {
        "Jméno": "Endy",
        "Pohlaví": "Samec",
        "Kraj": "Olomoucký",
        "Okres": "Olomouc",
        "Plemeno": "Irský setr",
        "Věk": "10 let",
        "Barva": "Červenohnědá",
        "Velikost": "Velká - 18 a více kg",
        "url": "https://www.psidetektiv.cz/zvire/endy-olomouc-2024-12-19",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190218.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190220.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190221.jpg"
        ]
    },
    "gigy-praha-vychod-2024-12-19": {
        "Jméno": "Gigy",
        "Pohlaví": "Samice",
        "Kraj": "Středočeský",
        "Okres": "Praha-východ",
        "Plemeno": "Kříženec",
        "Věk": "3 měsíce",
        "Barva": "Černo-hnědý",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/gigy-praha-vychod-2024-12-19",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190210.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190211.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190212.jpg"
        ]
    },
    "rey-praha-mesto-2024-12-18": {
        "Jméno": "Rey",
        "Pohlaví": "Samec",
        "Kraj": "Praha",
        "Okres": "Praha-město",
        "Plemeno": "Kříženec",
        "Věk": "3 roky",
        "Barva": "Krémová",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/rey-praha-mesto-2024-12-18",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190208.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190209.jpg"
        ]
    },
    "zelva-praha-zapad-2024-12-16": {
        "Jméno": "Želva",
        "Pohlaví": "Samice",
        "Kraj": "Středočeský",
        "Okres": "Praha-západ",
        "Plemeno": "Kříženec",
        "Věk": "3,5 roku",
        "Barva": "Želvovinová",
        "Velikost": "Malá - do 9kg",
        "url": "https://www.psidetektiv.cz/zvire/zelva-praha-zapad-2024-12-16",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190185.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/19/img190186.jpg"
        ]
    },
    "jeff-chelsea-matka-a-syn-kutna-hora-2024-12-18": {
        "Jméno": "Jeff a Chelsea",
        "Pohlaví": "Samec",
        "Kraj": "Středočeský",
        "Okres": "Kutná Hora",
        "Plemeno": "Kříženec",
        "Věk": "8 let a 9 let",
        "Barva": "Černý, bílé znaky",
        "Velikost": "Velká - 18 a více kg",
        "url": "https://www.psidetektiv.cz/zvire/jeff-chelsea-matka-a-syn-kutna-hora-2024-12-18",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190137.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190138.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190139.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190140.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190141.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190142.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190143.jpg"
        ]
    },
    "terina-vsetin-2024-12-17": {
        "Jméno": "Terina",
        "Pohlaví": "Samice",
        "Kraj": "Zlínský",
        "Okres": "Vsetín",
        "Plemeno": "Kříženec",
        "Věk": "10 let",
        "Barva": "Hnědá s bílými znaky",
        "Velikost": "Střední - 10-17kg",
        "url": "https://www.psidetektiv.cz/zvire/terina-vsetin-2024-12-17",
        "images": [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/17/img190110.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/17/img190111.jpg"
        ]
    }}

In [ ]:
first_3_pets = list(data.items())[:3].get(images)

In [75]:
import tensorflow as tf
import numpy as np
import tensorflow_hub as hub
import matplotlib.pyplot as plt



MODEL_URL = "https://tfhub.dev/tensorflow/ssd_mobilenet_v2/fpnlite_320x320/1"
detector = hub.load(MODEL_URL).signatures['serving_default']



In [52]:
import io
from PIL import Image, ExifTags

In [84]:
import tensorflow as tf
import numpy as np
from PIL import Image, ExifTags
import requests
import io

# Function to fix orientation using EXIF
def fix_orientation(image):
    try:
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation] == 'Orientation':
                break

        exif = image._getexif()
        if exif is not None:
            orientation = exif.get(orientation)
            if orientation == 3:
                image = image.rotate(180, expand=True)
            elif orientation == 6:
                image = image.rotate(270, expand=True)
            elif orientation == 8:
                image = image.rotate(90, expand=True)
    except (AttributeError, KeyError, IndexError):
        pass
    return image

# Function to crop and resize the image based on bounding box
def crop_and_resize(image, bounding_box, target_size):
    """
    Crop the image based on the bounding box (x1, y1, x2, y2) and resize it to the target size.
    """
    print("Original image shape:", image.shape)  # Debugging statement

    # Ensure the image is a TensorFlow tensor
    image = tf.convert_to_tensor(image, dtype=tf.float32)

    # Crop the image based on the bounding box (x1, y1, x2, y2)
    x1, y1, x2, y2 = bounding_box
    image = tf.strided_slice(image, [int(y1), int(x1), 0], [int(y2), int(x2), 3])  # Correctly slice the image
    print("Shape after cropping:", image.shape)  # Debugging statement

    # Resize the image to the target size
    image = tf.image.resize(image, target_size)
    print("Shape after resizing:", image.shape)  # Debugging statement

    return image

# Function to detect pets in the image (placeholder function, adjust as needed)
def detect_pet(image):
    """
    Runs object detection on the image and returns the bounding box of the pet if found.
    """
    # Resize and normalize the input image
    input_tensor = tf.image.resize(image, [640, 640]) / 255.0  # Resize for detector input
    input_tensor = tf.expand_dims(input_tensor, axis=0)  # Add batch dimension

    # Convert the tensor to uint8 (since the detector expects uint8)
    input_tensor_uint8 = tf.cast(input_tensor * 255.0, tf.uint8)  # Convert the float32 tensor to uint8

    # Run the detector
    result = detector(tf.convert_to_tensor(input_tensor_uint8))  # Call the model
    result = {key: value.numpy() for key, value in result.items()}  # Convert to numpy

    # Print the keys in the result to inspect the output
    print("Result keys:", result.keys())

    # Check if 'detection_classes' and 'detection_scores' are in the result
    if 'detection_classes' in result and 'detection_scores' in result:
        detected_classes = result['detection_classes']
        detected_boxes = result['detection_boxes']
        detected_scores = result['detection_scores']

        # Pet classes of interest, you may need to adjust this list
        pet_classes = [b"Cat", b"Dog", b"Animal"]  # Adjust based on your model's class names

        # Iterate through the detections and check if they are pets
        for idx in range(len(detected_classes[0])):
            detected_class = detected_classes[0][idx]  # First image in batch
            detected_score = detected_scores[0][idx]  # First image in batch
            detected_box = detected_boxes[0][idx]  # First image in batch

            # Check if the detection is a pet and has a high confidence score
            if detected_class in pet_classes and detected_score > 0.5:
                return detected_box  # Return the bounding box of the first detected pet

    else:
        print("The detection results do not contain the expected classes or boxes.")

    # If no pet detected, return None
    return None


# Function to download image and preprocess
def download_and_preprocess_image(url, target_size=(224, 224)):
    response = requests.get(url)
    image_bytes = response.content
    pil_image = Image.open(io.BytesIO(image_bytes))
    pil_image = fix_orientation(pil_image)

    # Convert image to tensor
    image = tf.convert_to_tensor(np.array(pil_image), dtype=tf.float32) / 255.0
    print("Shape of image after conversion:", image.shape)  # Debugging statement
    bounding_box = detect_pet(image)

    if bounding_box is not None:
        # If a pet is detected, crop and resize around it
        image = crop_and_resize(image, bounding_box, target_size)
    else:
        # If no pet is detected, fall back to center cropping
        image = tf.image.resize_with_crop_or_pad(image, target_size[0], target_size[1])

    # Return the correctly processed image (after cropping and resizing)
    print("Final processed image shape:", image.shape)  # Debugging statement
    return image

# Function to process images in parallel
def process_images_in_parallel(image_urls, target_size=(224, 224)):
    with concurrent.futures.ThreadPoolExecutor(max_workers=cpu_count()) as executor:
        processed_images = list(executor.map(lambda url: download_and_preprocess_image(url, target_size), image_urls))
    return processed_images


In [85]:
images = [download_and_preprocess_image(image) for image in [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190137.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190138.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190139.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190140.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190141.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190142.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190143.jpg"
        ]]

Shape of image after conversion: (311, 640, 3)
Result keys: dict_keys(['raw_detection_boxes', 'detection_multiclass_scores', 'detection_classes', 'detection_boxes', 'raw_detection_scores', 'num_detections', 'detection_anchor_indices', 'detection_scores'])
Final processed image shape: (224, 224, 3)
Shape of image after conversion: (480, 360, 3)
Result keys: dict_keys(['raw_detection_boxes', 'detection_multiclass_scores', 'detection_classes', 'detection_boxes', 'raw_detection_scores', 'num_detections', 'detection_anchor_indices', 'detection_scores'])
Final processed image shape: (224, 224, 3)
Shape of image after conversion: (480, 360, 3)
Result keys: dict_keys(['raw_detection_boxes', 'detection_multiclass_scores', 'detection_classes', 'detection_boxes', 'raw_detection_scores', 'num_detections', 'detection_anchor_indices', 'detection_scores'])
Final processed image shape: (224, 224, 3)
Shape of image after conversion: (480, 640, 3)
Result keys: dict_keys(['raw_detection_boxes', 'detectio

In [87]:
images_url = [
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190137.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190138.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190139.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190140.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190141.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190142.jpg",
            "https://www.psidetektiv.cz/data/catalog/big/2024/12/18/img190143.jpg"
        ]

In [88]:
process_images_in_parallel(images_url)

Shape of image after conversion:Shape of image after conversion: (311, 640, 3)
 (480, 360, 3)
Result keys: dict_keys(['raw_detection_boxes', 'detection_multiclass_scores', 'detection_classes', 'detection_boxes', 'raw_detection_scores', 'num_detections', 'detection_anchor_indices', 'detection_scores'])
Result keys: dict_keys(['raw_detection_boxes', 'detection_multiclass_scores', 'detection_classes', 'detection_boxes', 'raw_detection_scores', 'num_detections', 'detection_anchor_indices', 'detection_scores'])
Final processed image shape: (224, 224, 3)
Final processed image shape: (224, 224, 3)
Shape of image after conversion: (480, 360, 3)
Shape of image after conversion: (480, 640, 3)
Result keys: dict_keys(['raw_detection_boxes', 'detection_multiclass_scores', 'detection_classes', 'detection_boxes', 'raw_detection_scores', 'num_detections', 'detection_anchor_indices', 'detection_scores'])Result keys: dict_keys(['raw_detection_boxes', 'detection_multiclass_scores', 'detection_classes', '

[<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[    0.84706,     0.75294,     0.56471],
         [    0.84706,     0.75294,     0.56471],
         [    0.84706,     0.75294,     0.56471],
         ...,
         [    0.86275,     0.76471,     0.60392],
         [    0.87059,     0.77255,     0.61176],
         [    0.87059,     0.77255,     0.61176]],
 
        [[    0.84314,     0.74902,     0.56078],
         [    0.84314,     0.74902,     0.56078],
         [    0.83922,      0.7451,     0.55686],
         ...,
         [    0.89412,     0.78431,     0.62745],
         [     0.8902,     0.78039,     0.62353],
         [    0.88235,     0.77255,     0.61569]],
 
        [[    0.83922,      0.7451,     0.55686],
         [    0.83529,     0.74118,     0.55294],
         [    0.83529,     0.74118,     0.55294],
         ...,
         [     0.8902,     0.78039,     0.62353],
         [    0.87843,     0.76863,     0.61176],
         [    0.85882,     0.74902,     0.5921

In [102]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

def visualize_image(image, title="Processed Image"):
    """
    Visualizes an image using matplotlib.

    Arguments:
    image -- The image to visualize, can be a TensorFlow tensor or a NumPy array.
    title -- The title to display on top of the image.
    """
    print(f"Original type of image: {type(image)}")

    # Ensure the image is a NumPy array for visualization
    if isinstance(image, tf.Tensor):
        print("Converting TensorFlow tensor to NumPy array.")
        image = image.numpy()  # Convert TensorFlow tensor to NumPy array

    print(f"Image shape after conversion: {image.shape}")

    # If the image has a channel dimension, make sure it's in [0, 1] range
    if image.ndim == 3 and image.shape[-1] == 3:  # RGB image
        print("Image is RGB, clipping to [0, 1] range.")
        image = np.clip(image, 0, 1)
    elif image.ndim == 2:  # Grayscale image
        print("Image is grayscale, clipping to [0, 255] range and converting to uint8.")
        image = np.clip(image, 0, 255).astype(np.uint8)

    print(f"Image shape after clipping: {image.shape}")

    print("Min and Max pixel values after clipping:", np.min(image), np.max(image))

    # Check if the image array looks correct
    print("Image sample values:", image[:5, :5])  # Print a small portion of the image to verify content

    # Try showing the image explicitly with a different colormap if grayscale
    plt.imshow(image)
    plt.title(title)
    plt.axis("off")
    plt.show()



In [103]:
visualize_image(images[1])

Original type of image: <class 'tensorflow.python.framework.ops.EagerTensor'>
Converting TensorFlow tensor to NumPy array.
Image shape after conversion: (224, 224, 3)
Image is RGB, clipping to [0, 1] range.
Image shape after clipping: (224, 224, 3)
Min and Max pixel values after clipping: 0.0 1.0
Image sample values: [[[    0.42353     0.51373         0.2]
  [    0.67059     0.76078     0.43922]
  [    0.61569     0.70196     0.38039]
  [    0.67843     0.76471     0.43922]
  [    0.45882     0.53333     0.21176]]

 [[    0.38824     0.47843     0.16471]
  [    0.49412     0.58431     0.26275]
  [    0.60784     0.69412     0.36863]
  [    0.57255     0.65882     0.33333]
  [    0.43922     0.51765     0.18431]]

 [[    0.43529     0.51765     0.20784]
  [    0.36863      0.4549     0.13333]
  [    0.57647     0.65098     0.32941]
  [    0.61569      0.6902     0.36863]
  [    0.56471     0.64314      0.3098]]

 [[    0.38824     0.47451     0.15294]
  [    0.46275     0.54902     0.22